import { useQuery } from '@tanstack/react-query'
import { useParams } from 'react-router-dom'
import { CalendarDays, CarFront, MapPin, Phone } from 'lucide-react'
import { Container } from '@/components/ui/Container'
import { PageLoader } from '@/components/ui/PageLoader'
import { QueryError } from '@/components/ui/QueryState'
import { bookingApi } from '@/features/bookings/api'
import { formatMoney } from '@/lib/money'

export function BookingStatusPage(){const {bookingNumber='',token=''}=useParams();const query=useQuery({queryKey:['booking',bookingNumber,token],queryFn:()=>bookingApi.findPublic(bookingNumber,token),retry:false});if(query.isPending)return <PageLoader/>;if(query.isError)return <Container className="py-20"><QueryError retry={()=>void query.refetch()}/></Container>;const b=query.data;return <Container className="py-16 sm:py-24"><div className="mx-auto max-w-3xl"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm uppercase tracking-wider text-apricot">{b.booking_number}</p><h1 className="text-display mt-2 text-5xl">Your booking</h1></div><span className="rounded-full bg-forest px-4 py-2 text-sm font-bold capitalize text-white">{b.booking_status.replaceAll('_',' ')}</span></div><div className="mt-9 grid gap-4 sm:grid-cols-2"><Info icon={CalendarDays} label="Date & time" value={`${b.booking_date} · ${b.pickup_time.slice(0,5)}`}/><Info icon={CarFront} label="Car" value={b.car.name}/><Info icon={MapPin} label="Pickup" value={b.pickup.address}/><Info icon={Phone} label="Driver" value={b.driver?`${b.driver.name} · ${b.driver.phone}`:'Assigned after confirmation'}/></div><div className="mt-6 rounded-3xl bg-white p-6 shadow-soft"><div className="flex items-end justify-between"><div><p className="text-sm text-ink/50">Total</p><p className="mt-1 text-3xl font-bold text-forest">{formatMoney(b.price.total_minor,b.price.currency)}</p></div><div className="text-right text-sm text-ink/55"><p>Paid: {formatMoney(b.price.deposit_amount_minor,b.price.currency)}</p><p>Remaining: {formatMoney(b.price.total_minor-b.price.deposit_amount_minor,b.price.currency)}</p></div></div></div></div></Container>}
function Info({icon:Icon,label,value}:{icon:typeof CalendarDays;label:string;value:string}){return <div className="rounded-2xl bg-stone p-5"><Icon className="text-apricot"/><p className="mt-3 text-xs uppercase text-ink/45">{label}</p><p className="mt-1 font-semibold">{value}</p></div>}
