import { Briefcase, Snowflake, Users, Wifi } from 'lucide-react'
import { useQuery } from '@tanstack/react-query'
import { useTranslation } from 'react-i18next'
import { Link } from 'react-router-dom'
import { Container } from '@/components/ui/Container'
import { buttonStyles } from '@/components/ui/button-styles'
import { carsQuery } from '@/features/catalog/api'
import { formatMoney } from '@/lib/money'

export function CarsPage(){const {i18n}=useTranslation();const cars=useQuery(carsQuery({per_page:30}));return <Container className="py-16 sm:py-24"><p className="text-sm font-bold uppercase tracking-[.2em] text-apricot">Your private space</p><h1 className="text-display mt-3 text-5xl sm:text-6xl">Comfort for every road</h1><p className="mt-5 max-w-2xl text-lg text-ink/60">Choose the right capacity and comfort level. Tour prices are quoted for the entire car.</p><div className="mt-10 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{cars.data?.data.map(car=><article key={car.id} className="overflow-hidden rounded-3xl bg-white shadow-soft"><div className="grid h-52 place-items-center bg-stone">{car.cover_image?<img src={car.cover_image.url} alt={car.name} className="size-full object-cover"/>:<span className="text-display text-3xl text-forest/30">{car.category}</span>}</div><div className="p-6"><p className="text-xs font-bold uppercase tracking-wider text-apricot">{car.category}</p><h2 className="text-display mt-2 text-3xl">{car.name}</h2><div className="mt-5 grid grid-cols-2 gap-3 text-sm text-ink/60"><span className="flex gap-2"><Users className="size-4"/>{car.passenger_capacity} guests</span><span className="flex gap-2"><Briefcase className="size-4"/>{car.luggage_capacity} bags</span><span className="flex gap-2"><Snowflake className="size-4"/>A/C</span>{car.features.wifi&&<span className="flex gap-2"><Wifi className="size-4"/>Wi-Fi</span>}</div><p className="mt-6 text-sm text-ink/50">Services from <strong className="text-lg text-forest">{formatMoney(car.rates.base_minor,car.rates.currency,i18n.language)}</strong></p><Link to={`/booking?car=${car.id}`} className={`${buttonStyles('secondary')} mt-5 w-full`}>Choose this car</Link></div></article>)}</div></Container>}
