import { MessageCircle, ShieldCheck, Sparkles, Users } from 'lucide-react'
import { Container } from '@/components/ui/Container'
import { buttonStyles } from '@/components/ui/button-styles'

const values=[{icon:Users,title:'Local drivers',text:'Professional people who know the roads and the stories.'},{icon:ShieldCheck,title:'Clear and dependable',text:'Confirmed details, transparent prices, and direct support.'},{icon:Sparkles,title:'Made around you',text:'Your pace, pickup point, car, and route—not a crowded bus timetable.'}] as const

export function AboutPage(){return <Container className="py-16 sm:py-24"><div className="max-w-3xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-apricot">Local by nature</p><h1 className="text-display mt-3 text-5xl sm:text-7xl">Armenia, shared personally.</h1><p className="mt-6 text-xl leading-9 text-ink/60">We create private road journeys for travelers who value comfort, flexibility, and genuine local knowledge.</p></div><div className="mt-14 grid gap-5 md:grid-cols-3">{values.map(({icon:Icon,title,text})=><div key={title} className="rounded-3xl bg-white p-7 shadow-soft"><Icon className="text-apricot"/><h2 className="mt-4 text-xl font-bold">{title}</h2><p className="mt-3 leading-7 text-ink/60">{text}</p></div>)}</div></Container>}
export function ContactPage(){const number=import.meta.env.VITE_WHATSAPP_NUMBER??'37499123456';return <Container className="py-16 sm:py-24"><div className="mx-auto max-w-2xl text-center"><MessageCircle className="mx-auto size-12 text-apricot"/><h1 className="text-display mt-5 text-6xl">Let’s plan your Armenia trip.</h1><p className="mt-6 text-lg leading-8 text-ink/60">Ask about a route, luggage, child seats, airport pickup, or a special schedule. We’ll help you choose.</p><a className={`${buttonStyles()} mt-8`} href={`https://wa.me/${number}`} target="_blank" rel="noreferrer">Chat on WhatsApp</a></div></Container>}
const questions=[['How is the tour price calculated?','Most tours are priced per private car, not multiplied by passenger count. Per-person pricing is shown only when a tour specifically uses it.'],['Can you pick me up from my hotel?','Yes. Hotel, Airbnb, airport, and custom-address pickup are supported.'],['Can I change the route?','Yes. Use Build Your Trip or contact us for a flexible private itinerary.'],['When do I pay?','The initial MVP supports paying the driver. Deposit and full online payment architecture is prepared for later providers.'],['Can I cancel?','Each tour displays its free-cancellation window. Contact support as early as possible.']];
export function FaqPage(){return <Container className="py-16 sm:py-24"><div className="mx-auto max-w-3xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-apricot">Good to know</p><h1 className="text-display mt-3 text-6xl">Frequently asked questions</h1><div className="mt-10 divide-y divide-black/8 rounded-3xl bg-white px-6 shadow-soft">{questions.map(([q,a])=><details key={q} className="group py-6"><summary className="cursor-pointer list-none pr-8 text-lg font-bold">{q}</summary><p className="mt-3 leading-7 text-ink/60">{a}</p></details>)}</div></div></Container>}
