import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Link } from 'react-router-dom'
import { adminApi } from '@/features/admin/api'
import { StatusBadge } from '@/components/operations/StatusBadge'
import { formatMoney } from '@/lib/money'
import type { BookingStatus } from '@/types/domain'

export function AdminBookingsPage(){const [status,setStatus]=useState<BookingStatus|''>('');const [search,setSearch]=useState('');const [page,setPage]=useState(1);const query=useQuery({queryKey:['admin','bookings',{status,search,page}],queryFn:()=>adminApi.bookings({page,per_page:20,...(status?{booking_status:status}:{}),...(search?{search}:{})})});return <div><p className="text-sm font-semibold uppercase tracking-widest text-apricot">Operations</p><h1 className="mt-2 text-3xl font-bold">Bookings</h1><div className="mt-7 flex flex-wrap gap-3 rounded-2xl bg-white p-4"><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Booking, customer, phone..." className="min-h-11 min-w-60 flex-1 rounded-xl border border-black/10 px-4"/><select value={status} onChange={e=>{setStatus(e.target.value as BookingStatus|'');setPage(1)}} className="min-h-11 rounded-xl border border-black/10 px-4"><option value="">All statuses</option>{['pending','confirmed','assigned','driver_on_the_way','driver_arrived','in_progress','completed','cancelled','no_show'].map(item=><option value={item} key={item}>{item.replaceAll('_',' ')}</option>)}</select></div><div className="mt-5 overflow-hidden rounded-2xl bg-white shadow-sm"><div className="hidden grid-cols-[1.1fr_1.2fr_1fr_.8fr_.8fr] gap-4 border-b border-black/5 px-5 py-3 text-xs font-bold uppercase text-ink/40 md:grid"><span>Booking</span><span>Customer</span><span>Date</span><span>Total</span><span>Status</span></div>{query.data?.data.map(b=><Link to={`/admin/bookings/${b.id}`} key={b.id} className="grid gap-2 border-b border-black/5 px-5 py-4 hover:bg-stone/40 md:grid-cols-[1.1fr_1.2fr_1fr_.8fr_.8fr] md:items-center md:gap-4"><div><strong className="text-sm">{b.booking_number}</strong><p className="text-xs capitalize text-ink/45">{b.service_type.replaceAll('_',' ')}</p></div><div><p className="text-sm font-semibold">{b.customer.name}</p><p className="text-xs text-ink/45">{b.customer.phone}</p></div><p className="text-sm">{b.booking_date} · {b.pickup_time.slice(0,5)}</p><p className="text-sm font-semibold">{formatMoney(b.price.total_minor,b.price.currency)}</p><StatusBadge status={b.booking_status}/></Link>)}{query.data?.data.length===0&&<p className="p-10 text-center text-ink/45">No bookings match these filters.</p>}</div>{query.data&&query.data.meta.last_page>1&&<div className="mt-5 flex justify-end gap-2"><button disabled={page===1} onClick={()=>setPage(p=>p-1)} className="rounded-xl bg-white px-4 py-2 disabled:opacity-40">Previous</button><span className="px-3 py-2 text-sm">{page} / {query.data.meta.last_page}</span><button disabled={page===query.data.meta.last_page} onClick={()=>setPage(p=>p+1)} className="rounded-xl bg-white px-4 py-2 disabled:opacity-40">Next</button></div>}</div>}
