import { useMemo, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Link } from 'react-router-dom'
import { adminApi } from '@/features/admin/api'
import { StatusBadge } from '@/components/operations/StatusBadge'
import type { AdminBooking } from '@/types/domain'

function date(offset=0){const value=new Date();value.setDate(value.getDate()+offset);return value.toISOString().slice(0,10)}
export function AdminCalendarPage(){const [from,setFrom]=useState(date());const [to,setTo]=useState(date(14));const query=useQuery({queryKey:['admin','calendar',from,to],queryFn:()=>adminApi.calendar(from,to)});const data=query.data;const grouped=useMemo(()=>Object.entries((data??[]).reduce<Record<string,AdminBooking[]>>((days,item)=>{(days[item.booking_date]??=[]).push(item);return days},{})),[data]);return <div><p className="text-sm font-semibold uppercase tracking-widest text-apricot">Schedule</p><h1 className="mt-2 text-3xl font-bold">Booking calendar</h1><div className="mt-7 flex flex-wrap gap-3 rounded-2xl bg-white p-4"><label className="text-xs font-bold uppercase text-ink/45">From<input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="mt-1 block min-h-10 rounded-xl border border-black/10 px-3 text-sm font-normal text-ink"/></label><label className="text-xs font-bold uppercase text-ink/45">To<input type="date" value={to} onChange={e=>setTo(e.target.value)} className="mt-1 block min-h-10 rounded-xl border border-black/10 px-3 text-sm font-normal text-ink"/></label></div><div className="mt-5 grid gap-5 xl:grid-cols-2">{grouped.map(([day,bookings])=><section key={day} className="rounded-3xl bg-white p-5 shadow-sm"><h2 className="font-bold">{day}</h2><div className="mt-4 space-y-3">{bookings.map(item=><Link to={`/admin/bookings/${item.id}`} key={item.id} className="flex items-center justify-between gap-4 rounded-xl bg-stone/70 p-3"><div><p className="text-sm font-bold">{item.pickup_time.slice(0,5)} · {item.customer.name}</p><p className="mt-1 text-xs text-ink/45">{item.pickup.address}</p></div><StatusBadge status={item.booking_status}/></Link>)}</div></section>)}{!query.isPending&&grouped.length===0&&<p className="rounded-3xl bg-white p-10 text-center text-ink/45 xl:col-span-2">No bookings in this date range.</p>}</div></div>}
