import { useEffect, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ArrowDown, ArrowUp, ImagePlus, Pencil, Plus, Trash2, Video } from 'lucide-react'
import { useNavigate, useParams } from 'react-router-dom'
import { Button } from '@/components/ui/Button'
import { adminApi, type AdminTour, type TourAdminInput, type TourItineraryInput } from '@/features/admin/api'
import { toApiError } from '@/lib/api-client'
import { formatMoney, fromMinorUnits, toMinorUnits } from '@/lib/money'
import { Checkbox, NumberField, TextField, TranslationFields } from './AdminCatalogControls'
import { emptyTranslations, type LocalizedContent } from './admin-catalog-types'

interface TourForm extends Omit<TourAdminInput, 'starting_price_minor' | 'translations'> { starting_price:number; translations:LocalizedContent[] }

const emptyForm = (): TourForm => ({
  category_id:null, slug:'', duration_minutes:480, approximate_distance_km:null, starting_price:0,
  currency:'EUR', pricing_type:'per_car', format:'private', active:true, featured:false,
  start_time:null, meeting_point:null,
  max_passengers:4, pickup_available:true, dropoff_available:true, free_cancellation_hours:24,
  sort_order:0, translations:emptyTranslations(), itinerary:[],
})

function fromTour(tour:AdminTour):TourForm {
  return {...tour, itinerary:(tour.itinerary??[]).map(({destination_id,day_number,duration_minutes,optional,notes})=>({destination_id,day_number,duration_minutes,optional,notes})), starting_price:fromMinorUnits(tour.starting_price_minor,tour.currency), translations:emptyTranslations().map((empty) => {
    const translation=tour.translations.find((item) => item.locale===empty.locale)
    return {...empty, label:translation?.title??'', short_description:translation?.short_description??'', description:translation?.description??'', seo_title:translation?.seo_title??'', seo_description:translation?.seo_description??''}
  })}
}

function payload(form:TourForm):TourAdminInput {
  const {starting_price,translations,...fields}=form
  return {...fields,starting_price_minor:toMinorUnits(starting_price,form.currency),translations:translations.map(({label,...translation})=>({...translation,title:label,short_description:translation.short_description||null,description:translation.description||null,seo_title:translation.seo_title||null,seo_description:translation.seo_description||null}))}
}

function title(tour:AdminTour){return tour.translations.find((translation)=>translation.locale==='en')?.title??tour.slug}

export function AdminTourFormPage(){
  const {tourId}=useParams()
  return <AdminToursPage key={tourId??'new'} formPage />
}

export function AdminToursPage({ formPage = false }: { formPage?: boolean }){
  const navigate=useNavigate(); const {tourId}=useParams(); const routeTourId=tourId?Number(tourId):null
  const client=useQueryClient(); const queryKey=['admin','directory','tours'] as const
  const tours=useQuery({queryKey,queryFn:adminApi.tours}); const categories=useQuery({queryKey:['admin','tour-categories'],queryFn:adminApi.tourCategories}); const destinations=useQuery({queryKey:['admin','directory','destinations'],queryFn:adminApi.destinations})
  const [open,setOpen]=useState(formPage); const [editing,setEditing]=useState<number|null>(routeTourId); const [form,setForm]=useState<TourForm>(emptyForm); const [formReady,setFormReady]=useState(routeTourId===null); const [error,setError]=useState<string|null>(null)
  const editingSlug=tours.data?.data.find((tour)=>tour.id===editing)?.slug??''
  const mediaQuery=useQuery({queryKey:['admin','media','tours',editing],queryFn:()=>adminApi.tourMedia(editing as number,editingSlug),enabled:editing!==null&&editingSlug!==''})
  const refresh=async()=>client.invalidateQueries({queryKey})
  const refreshMedia=async()=>client.invalidateQueries({queryKey:['admin','media','tours']})
  const save=useMutation({mutationFn:()=>editing?adminApi.updateTour(editing,payload(form)):adminApi.createTour(payload(form)),onSuccess:async()=>{await refresh();if(formPage){void navigate('/admin/tours')}else{setOpen(false);setEditing(null)}},onError:(reason)=>setError(toApiError(reason).message)})
  const remove=useMutation({mutationFn:adminApi.deleteTour,onSuccess:refresh,onError:(reason)=>setError(toApiError(reason).message)})
  const uploadVideo=useMutation({mutationFn:({id,file}:{id:number;file:File})=>adminApi.uploadMedia('tours',id,file,'video'),onSuccess:async()=>{await Promise.all([refresh(),refreshMedia()])},onError:(reason)=>setError(toApiError(reason).message)})
  const uploadGallery=useMutation({mutationFn:async({id,files,startOrder}:{id:number;files:File[];startOrder:number})=>{for(const [index,file] of files.entries())await adminApi.uploadMedia('tours',id,file,'gallery',startOrder+index)},onSuccess:async()=>{await Promise.all([refresh(),refreshMedia()])},onError:(reason)=>setError(toApiError(reason).message)})
  const removeImage=useMutation({mutationFn:adminApi.deleteMedia,onSuccess:async()=>{await Promise.all([refresh(),refreshMedia()])},onError:(reason)=>setError(toApiError(reason).message)})
  const editingTour=tours.data?.data.find((tour)=>tour.id===editing)
  const gallery=mediaQuery.data?.filter((image)=>image.collection==='gallery')??editingTour?.gallery??[]
  const coverImage=mediaQuery.data?mediaQuery.data.find((image)=>image.collection==='cover')??null:editingTour?.cover_image??null
  const video=mediaQuery.data?mediaQuery.data.find((media)=>media.collection==='video')??null:editingTour?.video??null
  const slideshowImages=editingTour?[...(coverImage?[coverImage]:[]),...gallery.filter((image)=>image.id!==coverImage?.id)]:[]
  useEffect(()=>{if(!formPage||routeTourId===null||!tours.data||formReady)return;const timer=window.setTimeout(()=>{const tour=tours.data?.data.find((item)=>item.id===routeTourId);if(tour){setForm(fromTour(tour));setEditing(tour.id)}else{setError('Tour not found.')}setFormReady(true)},0);return()=>window.clearTimeout(timer)},[formPage,formReady,routeTourId,tours.data])
  function field<K extends keyof TourForm>(key:K,value:TourForm[K]){setForm((current)=>({...current,[key]:value}))}
  function itineraryField<K extends keyof TourItineraryInput>(index:number,key:K,value:TourItineraryInput[K]){field('itinerary',form.itinerary.map((stop,stopIndex)=>stopIndex===index?{...stop,[key]:value}:stop))}
  function addStop(){const destination=destinations.data?.data[0];if(!destination)return;field('itinerary',[...form.itinerary,{destination_id:destination.id,day_number:1,duration_minutes:null,optional:false,notes:null}])}
  function removeStop(index:number){field('itinerary',form.itinerary.filter((_,stopIndex)=>stopIndex!==index))}
  function moveStop(index:number,direction:-1|1){const target=index+direction;const current=form.itinerary[index];if(!current||target<0||target>=form.itinerary.length)return;const itinerary=[...form.itinerary];itinerary.splice(index,1);itinerary.splice(target,0,current);field('itinerary',itinerary)}
  function add(){void navigate('/admin/tours/new')}
  function edit(tour:AdminTour){void navigate(`/admin/tours/${tour.id}/edit`)}

  return <div><div className="flex flex-wrap items-end justify-between gap-4"><div>{formPage&&<button type="button" onClick={()=>void navigate('/admin/tours')} className="mb-3 text-sm font-bold text-forest">&larr; Back to tours</button>}<p className="text-sm font-semibold uppercase tracking-widest text-apricot">Catalog</p><h1 className="mt-2 text-3xl font-bold">{formPage?(editing?'Edit tour':'Add tour'):'Tours'}</h1></div>{!formPage&&<Button onClick={add}><Plus className="mr-2 size-4"/>Add tour</Button>}</div>
    {error&&<p className="mt-5 rounded-xl bg-red-50 p-4 text-sm text-danger">{error}</p>}
    {open&&!formReady&&<p className="mt-7 rounded-3xl bg-white p-6 text-sm text-ink/50 shadow-sm">Loading tour…</p>}
    {open&&formReady&&<form onSubmit={(event)=>{event.preventDefault();save.mutate()}} className="mt-7 rounded-3xl bg-white p-6 shadow-sm"><div><h2 className="text-xl font-bold">{editing?'Edit tour':'Add tour'}</h2></div>
      <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><TextField label="Slug" value={form.slug} onChange={(value)=>field('slug',value)} required/><label className="text-sm font-semibold">Category<select value={form.category_id??''} onChange={(event)=>field('category_id',event.target.value?Number(event.target.value):null)} className="mt-2 min-h-11 w-full rounded-xl border border-black/10 px-3"><option value="">No category</option>{categories.data?.map((category)=><option value={category.id} key={category.id}>{category.translations.find((item)=>item.locale==='en')?.name??category.slug}</option>)}</select></label>
        <label className="text-sm font-semibold">Tour type<select value={form.format} onChange={(event)=>field('format',event.target.value as TourForm['format'])} className="mt-2 min-h-11 w-full rounded-xl border border-black/10 px-3"><option value="private">Private</option><option value="group">Group</option></select></label>
        {form.format==='group'&&<><label className="text-sm font-semibold">Start time<input type="time" required value={form.start_time??''} onChange={(event)=>field('start_time',event.target.value||null)} className="mt-2 min-h-11 w-full rounded-xl border border-black/10 px-3"/></label><TextField label="Meeting place" value={form.meeting_point??''} onChange={(value)=>field('meeting_point',value||null)} required/></>}
        <label className="text-sm font-semibold">Pricing type<select value={form.pricing_type} onChange={(event)=>field('pricing_type',event.target.value as TourForm['pricing_type'])} className="mt-2 min-h-11 w-full rounded-xl border border-black/10 px-3"><option value="per_car">Per car</option><option value="per_person">Per person</option><option value="fixed">Fixed</option><option value="custom">Custom</option></select></label>
        <NumberField label={`Starting price (${form.currency})`} value={form.starting_price} onChange={(value)=>field('starting_price',value??0)} min={0} step={form.currency==='AMD'?'1':'0.01'} required/><label className="text-sm font-semibold">Currency<select value={form.currency} onChange={(event)=>field('currency',event.target.value as TourForm['currency'])} className="mt-2 min-h-11 w-full rounded-xl border border-black/10 px-3">{['EUR','USD','AMD'].map((currency)=><option key={currency}>{currency}</option>)}</select></label>
        <NumberField label="Duration (minutes)" value={form.duration_minutes} onChange={(value)=>field('duration_minutes',value??1)} min={1} required/><NumberField label="Distance (km)" value={form.approximate_distance_km} onChange={(value)=>field('approximate_distance_km',value)} min={0}/><NumberField label="Maximum passengers" value={form.max_passengers} onChange={(value)=>field('max_passengers',value)} min={1}/><NumberField label="Free cancellation (hours)" value={form.free_cancellation_hours} onChange={(value)=>field('free_cancellation_hours',value??0)} min={0} required/><NumberField label="Sort order" value={form.sort_order} onChange={(value)=>field('sort_order',value??0)} min={0} required/>
      </div><div className="mt-6 flex flex-wrap gap-5"><Checkbox label="Active" checked={form.active} onChange={(value)=>field('active',value)}/><Checkbox label="Featured" checked={form.featured} onChange={(value)=>field('featured',value)}/><Checkbox label="Pickup available" checked={form.pickup_available} onChange={(value)=>field('pickup_available',value)}/><Checkbox label="Drop-off available" checked={form.dropoff_available} onChange={(value)=>field('dropoff_available',value)}/></div>
      <section className="mt-7 rounded-2xl border border-black/8 bg-stone/45 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-bold">Itinerary</h3><p className="mt-1 text-sm text-ink/50">Add destinations in display order. Stops are automatically numbered within each day.</p></div><Button type="button" onClick={addStop} disabled={!destinations.data?.data.length}><Plus className="mr-2 size-4"/>Add destination</Button></div>
        {destinations.isPending&&<p className="mt-5 text-sm text-ink/50">Loading destinations…</p>}
        {!destinations.isPending&&form.itinerary.length===0&&<p className="mt-5 rounded-xl border border-dashed border-black/10 bg-white p-5 text-sm text-ink/50">No itinerary stops yet.</p>}
        <div className="mt-5 grid gap-4">{form.itinerary.map((stop,index)=><div key={index} className="rounded-xl bg-white p-4 shadow-sm"><div className="flex items-center justify-between gap-3"><p className="text-sm font-bold">Stop {index+1}</p><div className="flex items-center gap-1"><button type="button" onClick={()=>moveStop(index,-1)} disabled={index===0} aria-label="Move stop up" className="grid size-8 place-items-center rounded-full bg-black/5 disabled:opacity-30"><ArrowUp className="size-4"/></button><button type="button" onClick={()=>moveStop(index,1)} disabled={index===form.itinerary.length-1} aria-label="Move stop down" className="grid size-8 place-items-center rounded-full bg-black/5 disabled:opacity-30"><ArrowDown className="size-4"/></button><button type="button" onClick={()=>removeStop(index)} aria-label="Remove stop" className="grid size-8 place-items-center rounded-full bg-red-50 text-danger"><Trash2 className="size-4"/></button></div></div><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><label className="text-sm font-semibold sm:col-span-2">Destination<select required value={stop.destination_id} onChange={(event)=>itineraryField(index,'destination_id',Number(event.target.value))} className="mt-2 min-h-11 w-full rounded-xl border border-black/10 px-3">{destinations.data?.data.map((destination)=><option key={destination.id} value={destination.id}>{destination.translations.find((translation)=>translation.locale==='en')?.name??destination.slug}</option>)}</select></label><NumberField label="Day" value={stop.day_number} onChange={(value)=>itineraryField(index,'day_number',value??1)} min={1} required/><NumberField label="Duration (minutes)" value={stop.duration_minutes} onChange={(value)=>itineraryField(index,'duration_minutes',value)} min={1}/><div className="sm:col-span-2 lg:col-span-3"><TextField label="Notes" value={stop.notes??''} onChange={(value)=>itineraryField(index,'notes',value||null)}/></div><div className="flex items-end pb-3"><Checkbox label="Optional stop" checked={stop.optional} onChange={(value)=>itineraryField(index,'optional',value)}/></div></div></div>)}</div>
      </section>
      <TranslationFields noun="Tour title" value={form.translations} onChange={(value)=>field('translations',value)}/>
      {editingTour&&<section className="mt-7 rounded-2xl border border-black/8 bg-stone/45 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-bold">Tour detail video</h3><p className="mt-1 text-sm text-ink/50">Shown as the tour detail hero. The cover image remains the fallback.</p></div><label className="cursor-pointer rounded-full bg-forest px-4 py-2.5 text-sm font-bold text-white transition hover:bg-forest-light">{uploadVideo.isPending?'Uploading…':video?'Replace video':'Upload video'}<input type="file" accept="video/mp4,video/webm" className="hidden" onChange={(event)=>{const file=event.target.files?.[0];if(file)uploadVideo.mutate({id:editingTour.id,file});event.target.value=''}}/></label></div>{video?<div className="mt-5 overflow-hidden rounded-xl bg-white shadow-sm"><video src={video.url} controls preload="metadata" className="aspect-video w-full bg-black object-cover"/><div className="flex items-center justify-between px-3 py-2"><span className="text-xs font-semibold text-ink/50">MP4 or WebM · up to 100 MB</span><button type="button" onClick={()=>{if(window.confirm('Remove this tour video?'))removeImage.mutate(video.id)}} disabled={removeImage.isPending} className="rounded-full bg-red-50 px-3 py-2 text-xs font-bold text-danger disabled:opacity-40">Remove video</button></div></div>:<label className="mt-5 grid min-h-32 cursor-pointer place-items-center rounded-xl border-2 border-dashed border-black/10 bg-white text-center transition hover:border-forest/30"><span><Video className="mx-auto size-7 text-forest/40"/><span className="mt-2 block text-sm font-semibold text-ink/55">Click to upload a tour video</span><span className="mt-1 block text-xs text-ink/35">MP4 or WebM · up to 100 MB</span></span><input type="file" accept="video/mp4,video/webm" className="hidden" onChange={(event)=>{const file=event.target.files?.[0];if(file)uploadVideo.mutate({id:editingTour.id,file});event.target.value=''}}/></label>}</section>}
      {editingTour&&<section className="mt-7 rounded-2xl border border-black/8 bg-stone/45 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-bold">Slideshow images</h3><p className="mt-1 text-sm text-ink/50">The cover is shown first, followed by the gallery images. Select several new images at once.</p></div><label className="cursor-pointer rounded-full bg-forest px-4 py-2.5 text-sm font-bold text-white transition hover:bg-forest-light">{uploadGallery.isPending?'Uploading…':'Add slideshow images'}<input type="file" multiple accept="image/jpeg,image/png,image/webp" className="hidden" onChange={(event)=>{const files=Array.from(event.target.files??[]);if(files.length)uploadGallery.mutate({id:editingTour.id,files,startOrder:gallery.length});event.target.value=''}}/></label></div>{slideshowImages.length>0?<div className="mt-5 grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4">{slideshowImages.map((image,index)=><div key={image.id} className="group/image relative overflow-hidden rounded-xl bg-white shadow-sm"><img src={image.url} alt={image.alt_text??`${title(editingTour)} slide ${index+1}`} className="aspect-[4/3] w-full object-cover"/><div className="flex items-center justify-between px-3 py-2"><span className="text-xs font-semibold text-ink/50">{image.id===editingTour.cover_image?.id?'Cover · Slide 1':`Slide ${index+1}`}</span><button type="button" aria-label={`Remove ${image.id===editingTour.cover_image?.id?'cover image':`slide ${index+1}`}`} onClick={()=>{if(window.confirm('Remove this slideshow image?'))removeImage.mutate(image.id)}} disabled={removeImage.isPending} className="grid size-7 place-items-center rounded-full text-danger transition hover:bg-red-50 disabled:opacity-40"><Trash2 className="size-3.5"/></button></div></div>)}</div>:<label className="mt-5 grid min-h-32 cursor-pointer place-items-center rounded-xl border-2 border-dashed border-black/10 bg-white text-center transition hover:border-forest/30"><span><ImagePlus className="mx-auto size-7 text-forest/40"/><span className="mt-2 block text-sm font-semibold text-ink/55">Click to add slideshow images</span><span className="mt-1 block text-xs text-ink/35">JPG, PNG or WebP · up to 10 MB each</span></span><input type="file" multiple accept="image/jpeg,image/png,image/webp" className="hidden" onChange={(event)=>{const files=Array.from(event.target.files??[]);if(files.length)uploadGallery.mutate({id:editingTour.id,files,startOrder:0});event.target.value=''}}/></label>}</section>}
      <Button type="submit" disabled={save.isPending} className="mt-7">{save.isPending?'Saving…':'Save tour'}</Button>
    </form>}
    {!formPage&&<><div className="mt-7 overflow-hidden rounded-2xl bg-white shadow-sm">{tours.isPending&&<p className="p-5 text-sm text-ink/50">Loading tours…</p>}{tours.data?.data.map((tour)=><div key={tour.id} className="flex flex-wrap items-center justify-between gap-5 border-b border-black/5 px-5 py-4"><div className="flex items-center gap-4">{tour.cover_image?<img src={tour.cover_image.url} alt="" className="size-16 rounded-xl object-cover"/>:<div className="grid size-16 place-items-center rounded-xl bg-stone text-ink/30"><ImagePlus/></div>}<div><p className="font-semibold">{title(tour)}</p><p className="mt-1 text-xs text-ink/45">{tour.slug} · {tour.format} · {formatMoney(tour.starting_price_minor,tour.currency)}</p></div></div><div className="flex flex-wrap items-center gap-2"><button onClick={()=>edit(tour)} className="grid size-9 place-items-center rounded-full bg-black/5" aria-label="Edit tour"><Pencil className="size-4"/></button><button onClick={()=>{if(window.confirm(`Delete ${title(tour)}?`))remove.mutate(tour.id)}} className="grid size-9 place-items-center rounded-full bg-red-50 text-danger" aria-label="Delete tour"><Trash2 className="size-4"/></button></div></div>)}</div><p className="mt-4 text-sm text-ink/45">{tours.data?.total??0} total tours</p></>}
  </div>
}
