import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ImagePlus, Pencil, Plus, Trash2 } from 'lucide-react'
import { adminApi, type DirectoryItem, type DriverAdminInput } from '@/features/admin/api'
import { Button } from '@/components/ui/Button'
import { NumericInput } from '@/components/ui/NumericInput'
import { toApiError } from '@/lib/api-client'

type DriverForm = DriverAdminInput & { password: string }
const languageOptions = [['hy','Armenian'],['en','English'],['ru','Russian'],['fr','French'],['de','German'],['ar','Arabic'],['fa','Persian']] as const
const emptyForm: DriverForm = { first_name:'',last_name:'',phone:'',email:'',password:'',locale:'en',languages:['hy'],experience_years:0,license_number:'',rating:null,active:true,preferred_car_id:null,car_ids:[] }

function fromItem(item:DirectoryItem):DriverForm{return {first_name:item.first_name??'',last_name:item.last_name??'',phone:item.phone??'',email:item.email??'',password:'',locale:(item.locale??'en') as DriverForm['locale'],languages:item.languages??[],experience_years:item.experience_years??0,license_number:item.license_number??'',rating:item.rating??null,active:item.active,preferred_car_id:item.preferred_car_id??null,car_ids:item.car_ids??[]}}

export function AdminDriversPage(){
  const client=useQueryClient()
  const drivers=useQuery({queryKey:['admin','directory','drivers'],queryFn:()=>adminApi.directory('drivers')})
  const cars=useQuery({queryKey:['admin','directory','cars','driver-form'],queryFn:()=>adminApi.directory('cars')})
  const [editing,setEditing]=useState<number|null>(null);const [open,setOpen]=useState(false);const [form,setForm]=useState<DriverForm>(emptyForm);const [error,setError]=useState<string|null>(null)
  const refresh=async()=>client.invalidateQueries({queryKey:['admin','directory','drivers']})
  const save=useMutation({mutationFn:()=>{const {password,...values}=form;const input:DriverAdminInput=password?{...values,password}:values;return editing?adminApi.updateDriver(editing,input):adminApi.createDriver(input)},onSuccess:async()=>{await refresh();setOpen(false);setEditing(null);setForm(emptyForm)},onError:r=>setError(toApiError(r).message)})
  const remove=useMutation({mutationFn:adminApi.deleteDriver,onSuccess:refresh,onError:r=>setError(toApiError(r).message)})
  const upload=useMutation({mutationFn:({id,file}:{id:number;file:File})=>adminApi.uploadMedia('drivers',id,file,'profile'),onSuccess:refresh,onError:r=>setError(toApiError(r).message)})
  const removeImage=useMutation({mutationFn:adminApi.deleteMedia,onSuccess:refresh,onError:r=>setError(toApiError(r).message)})
  function field<K extends keyof DriverForm>(key:K,value:DriverForm[K]){setForm(current=>({...current,[key]:value}))}
  function add(){setEditing(null);setForm(emptyForm);setError(null);setOpen(true)}
  function edit(item:DirectoryItem){setEditing(item.id);setForm(fromItem(item));setError(null);setOpen(true)}
  function toggleCar(id:number){const selected=form.car_ids.includes(id);const car_ids=selected?form.car_ids.filter(value=>value!==id):[...form.car_ids,id];field('car_ids',car_ids);if(selected&&form.preferred_car_id===id)field('preferred_car_id',null)}
  return <div>
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-widest text-apricot">Team & fleet</p><h1 className="mt-2 text-3xl font-bold">Drivers</h1></div><Button onClick={add}><Plus className="mr-2 size-4"/>Add driver</Button></div>
    {error&&<p className="mt-5 rounded-xl bg-red-50 p-4 text-sm text-danger">{error}</p>}
    {open&&<form onSubmit={e=>{e.preventDefault();save.mutate()}} className="mt-7 rounded-3xl bg-white p-6 shadow-sm">
      <div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-apricot">Driver account</p><h2 className="mt-1 text-xl font-bold">{editing?'Edit driver':'Add driver'}</h2></div><button type="button" onClick={()=>setOpen(false)} className="text-sm font-bold text-ink/50">Close</button></div>
      <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        <Text label="First name" value={form.first_name} onChange={v=>field('first_name',v)} required/><Text label="Last name" value={form.last_name} onChange={v=>field('last_name',v)} required/><Text label="Phone" value={form.phone} onChange={v=>field('phone',v)} required/>
        <Text label="Login email" value={form.email} onChange={v=>field('email',v)} type="email" required/><Text label={editing?'New password (optional)':'Initial password'} value={form.password} onChange={v=>field('password',v)} type="password" required={!editing}/><Text label="Licence number" value={form.license_number} onChange={v=>field('license_number',v)} required/>
        <NumberField label="Experience (years)" value={form.experience_years} onChange={v=>{if(v!==null)field('experience_years',v)}} min={0} max={80}/><NumberField label="Rating" value={form.rating} onChange={v=>field('rating',v)} min={0} max={5} decimal/>
        <label className="text-sm font-semibold">Interface language<select value={form.locale} onChange={e=>field('locale',e.target.value as DriverForm['locale'])} className="mt-2 min-h-11 w-full rounded-xl border border-black/10 bg-white px-3"><option value="en">English</option><option value="ru">Russian</option><option value="hy">Armenian</option></select></label>
      </div>
      <div className="mt-6"><p className="text-sm font-semibold">Languages spoken</p><div className="mt-3 flex flex-wrap gap-2">{languageOptions.map(([code,label])=><button type="button" key={code} onClick={()=>field('languages',form.languages.includes(code)?form.languages.filter(v=>v!==code):[...form.languages,code])} className={`rounded-full px-4 py-2 text-sm font-bold transition ${form.languages.includes(code)?'bg-forest text-white':'bg-stone text-ink/55 hover:text-forest'}`}>{label}</button>)}</div></div>
      <div className="mt-6"><div className="flex items-center justify-between"><p className="text-sm font-semibold">Authorized cars</p><span className="text-xs text-ink/40">Select every car this driver may use</span></div><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{cars.data?.data.map(car=><button type="button" key={car.id} onClick={()=>toggleCar(car.id)} className={`rounded-2xl border p-4 text-left transition ${form.car_ids.includes(car.id)?'border-forest bg-forest/5':'border-black/8 hover:border-forest/30'}`}><span className="block font-bold">{car.brand} {car.model}</span><span className="mt-1 block text-xs text-ink/45">{car.plate_number}</span></button>)}</div></div>
      <div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Preferred car<select value={form.preferred_car_id??''} onChange={e=>{const id=e.target.value?Number(e.target.value):null;field('preferred_car_id',id);if(id&&!form.car_ids.includes(id))field('car_ids',[...form.car_ids,id])}} className="mt-2 min-h-11 w-full rounded-xl border border-black/10 bg-white px-3"><option value="">No preferred car</option>{cars.data?.data.filter(car=>form.car_ids.includes(car.id)).map(car=><option value={car.id} key={car.id}>{car.brand} {car.model} · {car.plate_number}</option>)}</select></label><label className="flex items-center gap-3 self-end rounded-2xl bg-stone px-4 py-3 text-sm font-semibold"><input type="checkbox" checked={form.active} onChange={e=>field('active',e.target.checked)} className="size-4"/>Active and allowed to log in</label></div>
      <Button type="submit" disabled={save.isPending} className="mt-7">{save.isPending?'Saving...':'Save driver'}</Button>
    </form>}
    <div className="mt-7 overflow-hidden rounded-2xl bg-white shadow-sm">{drivers.data?.data.map(item=><div key={item.id} className="flex flex-wrap items-center justify-between gap-5 border-b border-black/5 px-5 py-4"><div className="flex items-center gap-4">{item.profile_image?<img src={item.profile_image.url} alt="" className="size-16 rounded-2xl object-cover"/>:<div className="grid size-16 place-items-center rounded-2xl bg-stone text-ink/30"><ImagePlus/></div>}<div><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{item.first_name} {item.last_name}</p><span className={`rounded-full px-2 py-0.5 text-[11px] font-bold ${item.active?'bg-emerald-100 text-emerald-800':'bg-black/5 text-ink/45'}`}>{item.active?'Active':'Inactive'}</span>{item.telegram_connected&&<span className="rounded-full bg-sky-100 px-2 py-0.5 text-[11px] font-bold text-sky-800">Telegram</span>}</div><p className="mt-1 text-xs text-ink/45">{item.phone} · {item.email}</p><p className="mt-1 text-xs text-ink/40">{item.experience_years} years · {item.languages?.join(', ').toUpperCase()||'No languages'} · {item.cars?.map(car=>car.name).join(', ')||'No cars'}</p></div></div><div className="flex flex-wrap items-center gap-2"><label className="cursor-pointer rounded-full bg-black/5 px-3 py-2 text-xs font-bold text-ink/60">{item.profile_image?'Change photo':'Add photo'}<input type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={e=>{const file=e.target.files?.[0];if(file)upload.mutate({id:item.id,file});e.target.value='' }}/></label>{item.profile_image&&<button onClick={()=>{if(confirm('Remove this driver photo?'))removeImage.mutate(item.profile_image!.id)}} className="rounded-full bg-red-50 px-3 py-2 text-xs font-bold text-danger">Remove photo</button>}<button onClick={()=>edit(item)} className="grid size-9 place-items-center rounded-full bg-black/5" aria-label="Edit driver"><Pencil className="size-4"/></button><button onClick={()=>{if(confirm(`Delete ${item.first_name} ${item.last_name}?`))remove.mutate(item.id)}} className="grid size-9 place-items-center rounded-full bg-red-50 text-danger" aria-label="Delete driver"><Trash2 className="size-4"/></button></div></div>)}</div>
    <p className="mt-4 text-sm text-ink/45">{drivers.data?.total??0} total drivers</p>
  </div>
}

function Text({label,value,onChange,type='text',required=false}:{label:string;value:string;onChange:(value:string)=>void;type?:string;required?:boolean}){return <label className="text-sm font-semibold">{label}<input type={type} value={value} onChange={e=>onChange(e.target.value)} required={required} className="mt-2 min-h-11 w-full rounded-xl border border-black/10 px-3"/></label>}
function NumberField({label,value,onChange,min,max,decimal=false}:{label:string;value:number|null;onChange:(value:number|null)=>void;min:number;max:number;decimal?:boolean}){return <label className="text-sm font-semibold">{label}<NumericInput value={value} onValueChange={onChange} min={min} max={max} decimal={decimal} className="mt-2 min-h-11 w-full rounded-xl border border-black/10 px-3"/></label>}
